[general]
import = ["/home/toftpokk/.config/alacritty/colors.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
opacity = 0.8
