#!/bin/sh
print_battery(){
	if [ $1 -lt 9 ]; then
		printf "\\uf58d"
	elif [ $1 -lt 18 ]; then
		printf "\\uf579"
	elif [ $1 -lt 27 ]; then
		printf "\\uf57a"
	elif [ $1 -lt 36 ]; then
		printf "\\uf57b"
	elif [ $1 -lt 45 ]; then
		printf "\\uf57c"
	elif [ $1 -lt 54 ]; then
		printf "\\uf57d"
	elif [ $1 -lt 63 ]; then
		printf "\\uf57e"
	elif [ $1 -lt 72 ]; then
		printf "\\uf57f"
	elif [ $1 -lt 90 ]; then
		printf "\\uf57d"
	else
		printf "\\uf578"
	fi
}

case $BUTTON in
	1) powermenu;;
esac
if [ -f "/sys/class/power_supply/BAT0/charge_now" ]
then
	bat_now=$(cat /sys/class/power_supply/BAT0/charge_now)
	bat_full=$(cat /sys/class/power_supply/BAT0/charge_full)
	percent=$((bat_now * 100 / bat_full))
	icon=$(print_battery $percent)
	is_charging=$(cat /sys/class/power_supply/AC/online)
	printf "%2d%% $icon" "$percent"
	[ $is_charging = 1 ] && printf "\\uf0e7" || printf " "
	# Battery monitor
	[ $is_charging = 0 ] && [ $((bat_now*100/bat_full)) -lt 20  ] && dunstify -i "battery-symbolic.symbolic" -u "critical" -r 90212 "Battery" "Battery Low!"
else
	printf -- "--%% \uf590  " "$((95))"
fi
