#!/bin/sh

case $BUTTON in
	1) dislock;;
esac
status=$(xidlehook-client --socket /tmp/lockhook query | grep disabled | awk '{print $2}'| head -n1)

[ "$status" = "true," ] && printf "\\uf13e" || printf "\\uf023"
