#!/bin/sh

case $BUTTON in
	1) $TERMINAL -e pulsemixer;;
esac
vol="$(pamixer --get-volume)"
bar=$((vol*3/100))
icon=
case $bar in
	0) icon="\\ufc5c";;
	1) icon="\\ufa7e";;
	2) icon="\\ufa7f";;
	3) icon="\\ufa7d";;
esac
[ "$(pamixer --get-mute)" = "true" ] && icon="\\ufc5d"
printf "${icon}%3d%%" "${vol}"
