#!/bin/sh

case $BUTTON in
	1) wifi_view;;
esac
has_wifi=$(nmcli -f STATE,TYPE,CONNECTION dev | awk '/^connected\s+wifi/{print $3}')

printf "$has_wifi"
if [ -z "$has_wifi" ]
then
	printf " \\ufaa9 "
else
	printf " \\ufaa8 "
fi
