#!/bin/sh

set -euo pipefail

help(){
printf \
"Usage: $0 <destination ip or hostname>

Copies secrets from origin to destination

Secrets:
* .ssh/config
"
}

# Dest = 192.168.1.2 OR hostname
if [ ! "$#" -gt 0 ]; then
  echo "missing destination operand" >&2
  help
  exit 1
fi
DEST="$1"

read -p "Destination files will be removed. Are you sure? [Y/n]" -n 1 -r
echo
if [ "$REPLY" = "n" ]; then
  echo "Aborted"
  exit 1
fi


rsync "${HOME}/.ssh/config" "${DEST}:.ssh/config"

