#!/bin/sh

# Runs when start X Window System
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Compositor
picom &

# Caps to escape
setxkbmap -option caps:escape

if type screenlayout &> /dev/null; then
	screenlayout
fi

# Wallpaper
xwallpaper --zoom "$(cat ~/.config/wallpaper)"

# lockscreen
# lock &

fcitx5 -d &

# dwmblocks &
# exec dwm
eww open kong-bar
sxhkd &
exec bspwm
