#!/bin/sh
duration=2
(echo -e "%{c}${1}"; sleep ${duration}) | lemonbar -g 400x32+760+0 -o 0 -f "Hack Nerd Font"-20 -o -2 -f "Hack Nerd Font"-20 -f "Noto Serif CJK TC Medium"-20 -B "#282828" -F "#b8b8b8"
