#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config focused_border_color "#5066C6" # Focused Window
bspc config normal_border_color "#282828" # Normal Window
bspc config active_border_color "#b8b8b8" # Focused window in other monitor
bspc config presel_feedback_color "#383838"

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc subscribe desktop | while read line; do pkill lemonconfig -35; done &
# bspc subscribe node_focus | while read line; do pkill lemonconfig -35; done &
# bspc subscribe node_remove | while read line; do pkill lemonconfig -35; done &
bspc subscribe node | while read line; do pkill lemonconfig -35; done &
pgrep bspswallow || bspswallow &

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a openvpn desktop='^9'
bspc rule -a Zathura state=tiled
bspc rule -a obsidian state=tiled
bspc rule -a obsidian desktop='^4'
bspc rule -a anki desktop='^4'

autostart
