#!/bin/sh
# inspired by https://github.com/PoSayDone/

pactl subscribe | while read i; do
	case $i in
		*sink*)
			pactl get-sink-mute @DEFAULT_SINK@
			;;
		*source*)
			echo "s $i"
			;;
	esac
done;
