#!/bin/sh

bat=/sys/class/power_supply/BAT0/
per="$(cat "$bat/capacity")"

icon() {
	if [ "$per" -gt "90" ]; then
		icon=""
	elif [ "$per" -gt "80" ]; then
		icon=""
	elif [ "$per" -gt "70" ]; then
		icon=""
	elif [ "$per" -gt "65" ]; then
		icon=""
	elif [ "$per" -gt "60" ]; then
		icon=""
	elif [ "$per" -gt "50" ]; then
		icon=""
	elif [ "$per" -gt "40" ]; then
		icon=""
	elif [ "$per" -gt "30" ]; then
		icon=""
	elif [ "$per" -gt "20" ]; then
		icon=""
	elif [ "$per" -gt "10" ]; then
		icon=""
	else
		icon=""
	fi
	status=$(cat "$bat/status")
	[ "$status" = "Charging" ] && icon+="" || icon+=" "
	if [ "$per" -lt "20" ] && [ ! "$status" = "Charging" ]; then
		dunstify -i "battery-symbolic.symbolic" -u "critical" -r 90212 "Battery Low" "Connect Charger"
	fi
	echo "$per%$icon"
}

percent() {
	echo $per
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
exit
