#!/bin/env python
import subprocess
print('(box :class "workspace" :halign "start" :orientation "h" :space-evenly "false" ',end="")

desktops_out=subprocess.run(["bspc", "query","-D","--names"],capture_output=True).stdout
desktops = [ a for a in desktops_out.decode('utf-8').split('\n') if a != '']
focused_out=subprocess.run(["bspc", "query","-D","--names","-d","focused"],capture_output=True).stdout
focused = [ a for a in focused_out.decode('utf-8').split('\n') if a != '']
occupied_out=subprocess.run(["bspc", "query","-D","--names","-d",".occupied"],capture_output=True).stdout
occupied = [ a for a in occupied_out.decode('utf-8').split('\n') if a != '']

for d in range(0,len(desktops)):
    if desktops[d] in focused:
        print("(button :class 'focused' ",end="")
    elif desktops[d] in occupied:
        print("(button :class 'active' ",end="")
    else:
        print("(button ",end="")
    print(":onclick {'wmctrl -s "+str(d)+"'} '"+str(desktops[d])+"' ",end="")
    print(") ",end="")
print(")")
