#!/bin/sh

mimetype="$(file --mime-type -L -b -- "$1" )"
case $mimetype in
	application/json|application/x-ndjson|text/*|application/javascript|message/rfc822)
		highlight "$1" -s $HOME/.config/highlight/toft-colors.theme -O truecolor --force;;
  image/*)
    chafa -f sixels -s "$2x$3" --animate off --polite on "$1"
    exit 1
    ;;
  video/*)
    CACHE_DIR="$HOME/.cache/preview"
    mkdir -p "$CACHE_DIR"
    thumb="$CACHE_DIR/$(echo "$1" | sed 's/\//_/g')"
    # missing or outdated
    if [ ! -f "$thumb" ] || [ "$1" -nt "$thumb" ]; then 
      ffmpegthumbnailer -i "$1" -o "$thumb"
    fi
    chafa -f sixels -s "$2x$3" --animate off --polite on "$thumb"
    exit 1
    ;;
	audio/*) ~/.config/lf/scripts/audinfo "$1";;
	application/pdf) pdftotext -l 10 -nopgbrk -q -- "$1" -;;
  application/gzip|application/x-tar|application/zip|application/x-rar) printf "\e[0;29;44m Archived Files ($mimetype) \e[0m\n" && bsdtar --list --file "$1" ;;
	inode/x-empty) printf "\e[0;30;43m Empty \e[0m\n" ;;
  application/vnd.ms-opentype) fc-scan -b "$1";;
	application/x-executable) printf "\e[0;30;43m Executable \e[0m\n" ;;
	application/x-pie-executable) printf "\e[0;30;43m Pie Executable \e[0m\n" ;;
	*) printf "\e[0;33;40m $(file --dereference --brief -- "$1") \e[0m\n";;
esac
