#!/bin/sh

pathtoname() {
    udevadm info -p /sys/"$1" | awk -v FS== '/DEVNAME/ {print $2}'
}

list(){
	printf "(box :class 'disks' :orientation 'v' :space-evenly 'false'"
	# ls /run/media/$USER | xargs
	# if [ -z "$(ls -A /run/media/$USER)" ]; then
	# 	printf "''"
	# else
	# 	for i in /run/media/$USER/*; do
	# 		printf "(disk '$i') "
	# 	done
	# fi
	lsblk -rpo 'mountpoint,size,name,type' |
		awk '/^\//{printf "(disk :mountpoint `%s` :dev `%s` ) ",$1,$3}'


	echo ')'
}

list
stdbuf -oL -- udevadm monitor --udev -s block | while read -r -- _ _ event devpath _; do
		case "$event" in
			add)
				devname=$(pathtoname "$devpath")
				udisksctl mount --block-device "$devname" --no-user-interaction 2>/dev/null &&
					notify-send "Mounted" "Successfully mounted $devname"
				list
				;;
			remove)
				list
				;;
		esac
done
