#!/bin/sh

bat=/sys/class/power_supply/BAT0/
per="$(cat "$bat/capacity")"

icon() {
	status=$(cat "$bat/status")
	if [ "$per" -gt "90" ]; then
		icon="󰁹"
    [ "$status" = "Charging" ] && icon="󰂅"
	elif [ "$per" -gt "80" ]; then
		icon="󰂂"
    [ "$status" = "Charging" ] && icon="󰂋"
	elif [ "$per" -gt "70" ]; then
		icon="󰂁"
    [ "$status" = "Charging" ] && icon="󰂊"
	elif [ "$per" -gt "65" ]; then
		icon="󰂀"
    [ "$status" = "Charging" ] && icon="󰢞"
	elif [ "$per" -gt "60" ]; then
		icon="󰁿"
    [ "$status" = "Charging" ] && icon="󰂉"
	elif [ "$per" -gt "50" ]; then
		icon="󰁾"
    [ "$status" = "Charging" ] && icon="󰢝"
	elif [ "$per" -gt "40" ]; then
		icon="󰁽"
    [ "$status" = "Charging" ] && icon="󰂈"
	elif [ "$per" -gt "30" ]; then
		icon="󰁼"
    [ "$status" = "Charging" ] && icon="󰂇"
	elif [ "$per" -gt "20" ]; then
		icon="󰁻"
    [ "$status" = "Charging" ] && icon="󰂆"
	elif [ "$per" -gt "10" ]; then
		icon="󰁺"
    [ "$status" = "Charging" ] && icon="󰢜"
	else
		icon="󰂎"
    [ "$status" = "Charging" ] && icon="󰢟"
	fi

	if [ "$per" -lt "20" ] && [ ! "$status" = "Charging" ]; then
    # see https://github.com/emersion/mako/issues/252
		notify-send -i "battery-symbolic.symbolic" -u "critical" -r 90212 "Battery Low" "Connect Charger" --hint=string:x-dunst-stack-tag:battery \
      --hint=string:synchronous:battery
	fi
	echo "${icon} $per%"
}

percent() {
	echo $per
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
exit
