#!/bin/sh

[ "$#" -eq 0 ] && exit 1
[ "$1" = "unmount" ] && [ ! -z "$2" ] &&
	udisksctl unmount -b "$2" && notify-send "Unmounted" "Successfully unmounted $2" ||
	notify-send -u critical "Unmount Error" "Could not unmount $2"

