#!/bin/sh
usage(){
printf "Usage:	$0 rescan
	$0 networks
	$0 connect <SSID>
"
}
networks(){
	nmcli -t --fields IN-USE,SSID,SECURITY,BARS device wifi list ifname "wlp194s0" --rescan no
}

rescan(){
	nmcli --fields IN-USE,SSID,SECURITY,BARS device wifi list ifname "wlp194s0" --rescan yes >/dev/null &
}

try_store(){
	if [ $(nmcli dev wifi con "$1" | grep -c "successfully activated") -eq 1 ]; then
		notify-send "Connection Established"
		exit 0
	else
		notify-send "Connection Error: Unable to use stored credentials"
		exit 1
	fi
}
try_connect(){
	[ -z "$1" ] && exit
	if [ $(nmcli dev wifi con "$1" password "$2" | grep -c "successfully activated") -eq 1 ]; then
		notify-send "Connection Established"
		exit 0
	else
		notify-send "B Connection Error: Could not connect using password"
		exit 1
	fi
}
connect(){
	[ ! -z "$2" ] && [ ! -z "$1" ] && try_connect "$1" "$2" || try_store "$1"
}

disconnect(){
	dev=$(nmcli -fields TYPE,DEVICE d | grep "wifi " | awk '{print $2}')
	if nmcli dev disconnect "$dev" >/dev/null; then
		notify-send "Disconnected"
	else
		notify-send "Error"
	fi
}

connect_gui(){
	if [ "$(nmcli -f NAME con show | sed 's/\s//g' | grep "^${1}$" -c)" -eq 1 ]; then
		connect "$1"
	else
		printf "password: "
		read password
		connect "$1" "$password"
	fi
}
show(){
  nmcli -t -f name connection show --active | xargs
}

networks_gui(){
	#printf '(box "b")'
	x=$(networks)
	IFS=$'\n'
	printf '(box :class "network-scroll" :orientation "v" '
	for i in $x; do
		in_use=$(echo $i | cut -f 1 -d ':')
		ssid=$(echo $i | cut -f 2 -d ':')
		bars=$(echo $i | cut -f 4 -d ':')
    printf "(network :ssid \"%s\" :bars \"%s\"  " "${ssid//\"/\\\"}" "$bars"
		if [ $(echo "$in_use" | grep "\*" -c ) -eq 1 ]; then
			printf ":conn true "
		fi
		printf ") "
	done
	printf ')'
}
# printf "(box 'a')"
# networks_gui
# exit
[ "$#" -eq 0 ] && usage && exit 1
case "$1" in
	"rescan")
		rescan
		;;
	"networks")
		networks_gui
		;;
	"connect")
		connect_gui "$2" &
		;;
	"disconnect")
		disconnect &
		;;
	"show")
		show
		;;
esac
