#!/bin/sh
# inspired by https://github.com/PoSayDone/

workspaces(){
	printf '(box :class "workspace" :halign "start" :orientation "h" :space-evenly "false" '
	desktops=$(bspc query -D --names)
	focused=$(bspc query -D --names -d focused)
	occupied=$(bspc query -D --names -d .occupied)
	for d in $desktops; do
		#printf "(button '$d') "
		if echo $focused | grep -w -q $d; then
			printf "(button :class 'focused' "
		elif echo $occupied | grep -w -q $d; then
			printf "(button :class 'active' "
		else
			printf "(button "
		fi
		printf ":onclick {'wmctrl -s '+($d-1 < 0 ? 9 : $d-1)} '$d') "
	done
	echo ')'
}
workspaces
xprop -spy -root _NET_ACTIVE_WINDOW | while read -r _ ; do
	workspaces
done
