#!/bin/sh

bright=$(printf '%.0f' $(xbacklight -get))
dunstify -a "brightness" -u low -i display-brightness-symbolic.symbolic \
	-h string:x-dunst-stack-tag:brightness \
	-h int:value:$bright "Brightness"
canberra-gtk-play -i audio-volume-change -d "volume"
