#!/bin/sh

vol="$(pamixer --get-volume)"
if [ "$(pamixer --get-mute)" = "true" ] || [ $vol -eq 0 ]; then
	dunstify -a "volume" -u low -i audio-volume-muted-symbolic.symbolic \
		-h string:x-dunst-stack-tag:volume \
		"Volume Muted"
else
	dunstify -a "volume" -u low -i audio-volume-high-symbolic.symbolic \
		-h string:x-dunst-stack-tag:volume \
		-h int:value:$vol "Volume $vol%"
fi
canberra-gtk-play -i audio-volume-change -d "volume"
