#!/bin/sh
# Based on chris@machine's config https://www.youtube.com/watch?v=bTLYiNvRIVI

setopt autocd extendedglob nomatch menucomplete interactivecomments
setopt hist_ignore_dups

# disable ctrl-s to freeze terminal (note: ctrl-q to resume)
stty stop undef

zle_highlight=('paste:none') # disable paste highlight

unsetopt BEEP # disable beep

#### COMPLETIONS ####
autoload -Uz compinit

# menu selection will start automatically
zstyle ':completion:*' list-colors "di=01;34"
zstyle ':completion:*' menu select
zstyle ':completion:*' completer _complete _approximate _ignored

# complist defines menuselect
zmodload zsh/complist
_comp_options+=(globdots) # include hidden files

compinit

autoload -Uz colors && colors

#### ALASES ####
alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias cp="cp -i" # Confirm copy
alias df="df -h" # Human readable
alias diff='diff --color=auto'

alias v="nvim"
alias vim="nvim"
alias ..="cd .."
alias n="notes"
alias b="blog"

#### Keybinds ####
bindkey -M menuselect '^[[Z' reverse-menu-complete # Shift-tab reverse menu

# Control Left/Right
bindkey -e # disable vim mode

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey '^a' beginning-of-line #  go to beginning
bindkey '^e' end-of-line # go to end

bindkey "^[[3~" delete-char # delete char
bindkey "^[[3;5~" kill-word # control delete word
bindkey '^H' backward-kill-word # Delete word back
bindkey '^r' history-incremental-search-backward # backward search

# exit zsh
exit_zsh() { exit }
zle -N exit_zsh
bindkey '^D' exit_zsh

PROMPT='%B%F{red}%n%f%F{green}@%m%f %c%F{green}%#%f%b '
HISTFILE="$XDG_STATE_HOME/zsh/history"
HISTSIZE=1000000
SAVEHIST=1000000

[ -f "$XDG_CONFIG_HOME/private_env" ] && source "$XDG_CONFIG_HOME/private_env"
