#!/usr/bin/env python
"""
Script to add zero padding to numeric filename
only valid in certain contexts

running:

    ./change-num.py directory

where:

    directory/
        1.png
        3.jpg
        100.png
to:

    directory/
        001.png
        003.jpg
        100.png
"""
from sys import argv,exit
import os

# Check path
if len(argv) < 2:
    print("Error: No path provided")
    exit(1)
path=argv[1]
if not os.path.isdir(path):
    print(f"Error: '{path}' is not a directory")
    exit(1)

filelist = os.listdir(path)
# Check files
max_n = -1
for file in filelist:
    fn = file.split(".")
    if len(fn) < 2:
        print(f"Error: '{file}' has no extension")
        print("Are you in the wrong directory?")
        exit(1)
    try:
        num = int(fn[0])
    except:
        print(f"Error: '{file}' is not a valid filename")
        print("Are you in the wrong directory?")
        exit(1)
    if num > max_n:
        max_n = num
if max_n == -1:
    print("Error no valid file found")
    exit(1)

# Running
digits = len(str(max_n)) # magic
for file in filelist:
    fn = file.split(".")
    name = fn[0]
    new_name = name.zfill(digits)
    if name == new_name:
        continue
    new_file = new_name+"."+".".join(fn[1:])
    new_file_path = os.path.join(path,new_file)
    old_file_path = os.path.join(path,file)
    os.rename(old_file_path,new_file_path)
    
