#!/bin/sh

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/dmenu_often"

programs="$(dmenu_path)"

sel=$(echo -e "$(cat $cache)\n$programs" | dmenu "$@")
echo "$sel" | ${SHELL:-"/bin/sh"} &
[ -z "$sel" ] && exit
newstore="$sel"

cnt=0
while read line; do
	[ "$sel" = "$line" ] && continue
	newstore="${newstore}\n${line}"
	cnt=$((cnt+1))
	[ $cnt -gt 5 ] && break
done < $cache
echo -e "$newstore" > "$cache"
