#!/bin/sh
set -euo pipefail

error_exit() {
	echo "$1" >&2
	exit 1
}
usage() {
	echo "usage: $(basename "$0") [ -h help ] target"
}

help() {
	echo "Usage:
    $0 filename"
}

exdir="."
if [ ! -z "${2:-}" ]; then
	if [ -d "$2" ]; then
		exdir="$2"
	else
		echo "No dir $2"
		exit
	fi
fi

if [ -f "$1" ]; then
  OUTPUT=""
  exit_code=0
	case "$1" in
    *.tar.bz2)            OUTPUT="$(tar xjf "$1" --directory="$exdir" 2>&1)"|| exit_code=$? ;;
    *.tar.gz)             OUTPUT="$(tar xzf "$1" --directory="$exdir" 2>&1)"|| exit_code=$? ;;
    *.tar.xz | *.tar.zst) OUTPUT="$(tar xf "$1" --directory="$exdir" 2>&1)"|| exit_code=$? ;;
    *.bz2)                OUTPUT="$(bunzip2 "$1" 2>&1)"|| exit_code=$? ;;
    *.rar)                OUTPUT="$(unrar x "$1" "$exdir" 2>&1)"|| exit_code=$? ;;
    *.gz)                 OUTPUT="$(gunzip "$1" 2>&1)"|| exit_code=$? ;;
    *.tar)                OUTPUT="$(tar xf "$1" --directory="$exdir" 2>&1)"|| exit_code=$? ;;
    *.tbz2)               OUTPUT="$(tar xjf "$1" --directory="$exdir" 2>&1)"|| exit_code=$? ;;
    *.tgz)                OUTPUT="$(tar xzf "$1" --directory="$exdir" 2>&1)"|| exit_code=$? ;;
    *.zip | *.cbz)        OUTPUT="$(unzip "$1" -d "$exdir" 2>&1 >/dev/null)" || exit_code=$? ;;
    *.Z)                  OUTPUT="$(uncompress "$1" 2>&1)"|| exit_code=$? ;;
    *.7z)                 OUTPUT="$(7z x "$1" 2>&1)"|| exit_code=$? ;;
	*)
		error_exit "'$1' cannot be extracted via ex()"
		;;
	esac
  if [ "$exit_code" -ne 0 ]; then
    notify-send -u critical "Extract" "$OUTPUT"
    error_exit "$OUTPUT"
  fi
else
	error_exit "'$1' is not a valid file"
fi
filename=$(basename -- "${1}")
notify-send "Extract" "Finished extracting ${filename}"
