#!/bin/sh
# Inspired by neofetch
board_name=$(cat /sys/devices/virtual/dmi/id/board_name)
board_vendor=$(cat /sys/devices/virtual/dmi/id/board_vendor)
product_name=$(cat /sys/devices/virtual/dmi/id/product_name)
cpu_file="/proc/cpuinfo"
cpu=$(awk -F '\\s*: | @' \
                            '/model name|Hardware|Processor|^cpu model|chip type|^cpu type/ {
                            cpu=$2; if ($1 == "Hardware") exit } END { print cpu }' $cpu_file)
cpu_cores=$(cat /proc/cpuinfo | grep -c "^processor")
gpu_cmd="$(lspci -mm |
           awk -F '\"|\" \"|\\(' \
                  '/"Display|"3D|"VGA/ {
                      a[$0] = $1 " " $3 " " ($(NF-1) ~ /^$|^Device [[:xdigit:]]+$/ ? $4 : $(NF-1))
                  }
                  END { for (i in a) {
                      if (!seen[a[i]]++) {
                          sub("^[^ ]+ ", "", a[i]);
                          print a[i]
                      }
                  }}')"
IFS=$'\n' read -d "" -ra gpus <<< "$gpu_cmd"
mem_available="$(cat /proc/meminfo | grep MemAvailable | sed -e 's/MemAvailable:\s*\([0-9]*\).*/\1/')"
mem_total="$(cat /proc/meminfo | grep MemTotal | sed -e 's/MemTotal:\s*\([0-9]*\).*/\1/')"

mem_used="$(((mem_total - mem_available) / 1024))"
mem_total="$((mem_total / 1024))"
mem_perc="$(((mem_used*100)/mem_total))"

disk="$(df -h --output=file,source,used,size / | tail -n 1 | awk '{ print $1,  $2,  $3 "/" $4 " (" int($3*100/$4) "%)" }')"

install_date="$(cat /var/log/pacman.log |
  head -n 1 |
  sed -e 's/^\[\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}[+-][0-9]\{2\}[0-9]\{2\}\).*/\1/g' )"

days_since="$(( ($(date +%s) - $(date +%s -ud ${install_date})) / 3600 / 24 ))"

echo "\
CPU: $cpu ($cpu_cores)
Mainboard: $board_name $board_vendor
Product: $product_name
GPU:$gpus
Memory: ${mem_used}/${mem_total} MiB (${mem_perc}%)
Disk: ${disk}
Installed At: ${install_date} (${days_since} days ago)\
"
