#!/bin/bash

find_ntsc_perc(){
  edid="$1"
  colors="$(echo "$edid" |  grep "Color Characteristics" -A 4 | head -n 4 | tail -n 3)"
  redx="$(echo "$colors" | awk '/Red/ {print substr($3, 1, length($3)-1)}')"
  redy="$(echo "$colors" | awk '/Red/ {print $4}')"
  bluex="$(echo "$colors" | awk '/Blue/ {print substr($3, 1, length($3)-1)}')"
  bluey="$(echo "$colors" | awk '/Blue/ {print $4}')"
  # note: green has no space between key and value
  greenx="$(echo "$colors" | awk '/Green/ {print substr($2, 1, length($3)-1)}')"
  greeny="$(echo "$colors" | awk '/Green/ {print $3}')"
  ntsc_area="0.1581936030502012"
  echo "print(int(abs(0.5*($redx*($greeny-$bluey)+$greenx*($bluey-$redy)+$bluex*($redy-$greeny)))/$ntsc_area *100))" | python3
}

# Inspired by neofetch
board_name=$(cat /sys/devices/virtual/dmi/id/board_name)
board_vendor=$(cat /sys/devices/virtual/dmi/id/board_vendor)
product_name=$(cat /sys/devices/virtual/dmi/id/product_name)
cpu_file="/proc/cpuinfo"
cpu=$(awk -F '\\s*: | @' \
                            '/model name|Hardware|Processor|^cpu model|chip type|^cpu type/ {
                            cpu=$2; if ($1 == "Hardware") exit } END { print cpu }' $cpu_file)
cpu_cores=$(cat /proc/cpuinfo | grep -c "^processor")
gpu_cmd="$(lspci -mm |
           awk -F '\"|\" \"|\\(' \
                  '/"Display|"3D|"VGA/ {
                      a[$0] = $1 " " $3 " " ($(NF-1) ~ /^$|^Device [[:xdigit:]]+$/ ? $4 : $(NF-1))
                  }
                  END { for (i in a) {
                      if (!seen[a[i]]++) {
                          sub("^[^ ]+ ", "", a[i]);
                          print a[i]
                      }
                  }}')"
IFS=$'\n' read -d "" -ra gpus <<< "$gpu_cmd"
mem_available="$(cat /proc/meminfo | grep MemAvailable | sed -e 's/MemAvailable:\s*\([0-9]*\).*/\1/')"
mem_total="$(cat /proc/meminfo | grep MemTotal | sed -e 's/MemTotal:\s*\([0-9]*\).*/\1/')"

mem_used="$(((mem_total - mem_available) / 1024))"
mem_total="$((mem_total / 1024))"
mem_perc="$(((mem_used*100)/mem_total))"

disk="$(df -h --output=file,source,used,size / | tail -n 1 | awk '{ print $1,  $2,  $3 "/" $4 " (" int($3*100/$4) "%)" }')"

install_date="$(cat /var/log/pacman.log |
  head -n 1 |
  sed -e 's/^\[\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}[+-][0-9]\{2\}[0-9]\{2\}\).*/\1/g' )"

days_since="$(( ($(date +%s) - $(date +%s -ud ${install_date})) / 3600 / 24 ))"
primary_monitor="$(xrandr | awk '/ connected / {print $1}' | head -n 1)"
primary_monitor_info="$(cat /sys/class/drm/card1-${primary_monitor}/edid | edid-decode )"
size_and_freq="$(echo "$primary_monitor_info" | awk '/DTD/{print $3 " @" $4 $5}')"
ntsc_perc=$(find_ntsc_perc "$primary_monitor_info")

echo "\
CPU: $cpu ($cpu_cores)
Mainboard: $board_name $board_vendor
Product: $product_name
GPU:$gpus
Monitor: ${primary_monitor} ${size_and_freq} NTSC${ntsc_perc}%
Memory: ${mem_used}/${mem_total} MiB (${mem_perc}%)
Disk: ${disk}
Installed At: ${install_date} (${days_since} days ago)\
"
