#!/bin/sh
# Inspired by neofetch
board_name=$(cat /sys/devices/virtual/dmi/id/board_name)
board_vendor=$(cat /sys/devices/virtual/dmi/id/board_vendor)
cpu_file="/proc/cpuinfo"
cpu=$(awk -F '\\s*: | @' \
                            '/model name|Hardware|Processor|^cpu model|chip type|^cpu type/ {
                            cpu=$2; if ($1 == "Hardware") exit } END { print cpu }' $cpu_file)
cpu_cores=$(cat /proc/cpuinfo | grep -c "^processor")
gpu_cmd="$(lspci -mm |
           awk -F '\"|\" \"|\\(' \
                  '/"Display|"3D|"VGA/ {
                      a[$0] = $1 " " $3 " " ($(NF-1) ~ /^$|^Device [[:xdigit:]]+$/ ? $4 : $(NF-1))
                  }
                  END { for (i in a) {
                      if (!seen[a[i]]++) {
                          sub("^[^ ]+ ", "", a[i]);
                          print a[i]
                      }
                  }}')"
IFS=$'\n' read -d "" -ra gpus <<< "$gpu_cmd"
mem_available="$(cat /proc/meminfo | grep MemAvailable | sed -e 's/MemAvailable:\s*\([0-9]*\).*/\1/')"
mem_total="$(cat /proc/meminfo | grep MemTotal | sed -e 's/MemTotal:\s*\([0-9]*\).*/\1/')"

mem_used="$(((mem_total - mem_available) / 1024))"
mem_total="$((mem_total / 1024))"

disk="$(df -h --output=file,source,used,avail / | tail -n 1)"

echo "\
CPU: $cpu ($cpu_cores)
Mainboard: $board_name $board_vendor
GPU:$gpus
Memory: ${mem_used}MiB/${mem_total}
Disk: ${disk} \
"
