#!/bin/sh
swaylock -f --screenshots \
        --clock \
        --indicator \
        --effect-blur 7x5 \
        --effect-vignette 0.5:0.5 \
        --ring-color 5066C6 \
        --key-hl-color 70CCAD \
        --fade-in 0.2 \
