#!/bin/sh

if [ -z "$1" ]; then
  wifi_con="$(nmcli -t connection show --active | grep wireless | cut -d: -f 1,1)"
  case "$wifi_con" in
    "Nartnet-5G"|"Nartnet-2.5G")
      mode="home";;
    *)
      mode="work";;
  esac
else
  mode="$1"
fi

case "$mode" in
  "home")
    wallpaper ~/Backgrounds/cultured ~/Backgrounds/unsafe
    ;;
  "work")
    wallpaper
    ;;
  "dark")
    sed -i "s/^colors: \*.*/colors: *dark/" $XDG_CONFIG_HOME/alacritty/colors.yml
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    ;;
  "light")
    sed -i "s/^colors: \*.*/colors: *light/" $XDG_CONFIG_HOME/alacritty/colors.yml
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    ;;
esac
