#!/bin/sh

# disks=$(lsblk -rpo 'name,type,size,mountpoint' | grep part | awk '{printf "%s (%s)+",$1,$3}')

# disk=$(echo $disks | sed 's/+/\n/g' | dmenu -p "Disk to mount: ") || exit 1
# disk=$(echo $disk | awk '{print $1}')
disks=$(lsblk -rpo name,type,size,label | awk '/part/{if($4 != ""){printf "%s (%s %s)\n",$1,$4,$3}else{printf "%s (%s)\n",$1,$3}}' | sed 's/\\x20/_/g' | dmenu) || exit 1
disks=$(echo $disks | awk '{print $1}')

points=("/mnt/usb1" "/mnt/usb2" "/mnt/usb3" "/")
# mountpoint=$(echo "/mnt/usb1 /mnt/usb2 /mnt/usb3" | sed "s/ /\n/g" | dmenu -fn "monospace:size=15" -p "Mountpoint: ") || exit 1
udisksctl mount -b "$disks" && notify-send -i "drive-harddisk-symbolic.symbolic" "Mount" "Mounted Disk $disk" || notify-send -i "dialog-warning-symbolic.symbolic" -u "critical" "Mount" "Could not mount ${1}" && exit 1
