#!/bin/sh

help(){
printf "
Usage:
 music <list>

Play music from nfs server.

Sample Config file:

  #!/bin/sh
  playlist=('jp')

  PLAYLIST_jp(){
    mount ~/Music && mpv --shuffle /path/to/music --audio-display=no
  }

"
}

: ${XDG_CONFIG_HOME:=$HOME/.config}

if [ -f "${XDG_CONFIG_HOME}/music/config.conf" ]; then
  source "${XDG_CONFIG_HOME}/music/config.conf"
else
  echo "Error: Config file not found"
  help
  exit 1
fi

lists="${playlist[@]}"

found=0
for list in "${playlist[@]}"; do
  if [ "$1" = "$list" ]; then
    eval "PLAYLIST_$1"
  fi
done

if [ "$found" -eq 0 ]; then
  echo "Error: List not found"
  help
  echo "Available lists:
  ${lists}
"
fi
