#!/bin/sh
icon_range(){
  j=0
	for i in $(seq $1 $2); do
    printf "\\u$(printf "%x" $i)  "
    # --- Newline every 20 characters
    if [ "$j" -eq 20 ]; then
      printf "\n$((i+1)) %x " $i && j=0
    fi
    j=$((j+1))
    # ---
  done
}

allfonts=
# Language parts 0-57344
icon_range 57344 59333
icon_range 59333 64838
# Language parts 64838-65600 END
printf "$allfonts"
