#!/bin/sh

perc="$(pamixer --get-volume)"
message=""
if [ "$(pamixer --get-mute)" = "true" ] || [ $perc -eq 0 ]; then
	message="Volume Muted"
else
	message="Volume $vol%"
fi
notify-send -a "volume" \
  -u low \
  -i audio-volume-high-symbolic \
	-h string:x-dunst-stack-tag:volume \
	-h int:value:$vol $message
  canberra-gtk-play -i audio-volume-change -d "volume"
