#!/bin/sh
# NSXIV Script rifle modified
# Source: https://codeberg.org/nsxiv/nsxiv-extra/src/branch/master/scripts/nsxiv-rifle/nsxiv-rifle

tmp="/tmp/nsxiv_rifle_$$"

listfiles() {
  find -L "${1%/*}" -maxdepth 1 -type f -print |
    grep -iE '\.(jpe?g|png|gif|webp|tiff|bmp|svg)$' |
    sort | tee "$tmp"
}

open_img() {
  trap 'rm -f $tmp' EXIT
  count="$(listfiles "$1" | grep -nF "$1")"
  if [ -n "$count" ]; then
    # nsxiv -o -i -n "${count%%:*}" -- < "$tmp"
	selection="$(nsxiv -a -o -i - -n "${count%%:*}" -- < "$tmp")"
	if [ ! -z "$selection" ]; then
		# printf "$selection"
		first="${selection/$'\n'*/}"
		lf -remote "send $id select \"$first\""
		IFS=$'\n'
		for i in $selection; do
			lf -remote "send $id glob-select \"${i##*/}\""
		done
	fi
  else
    nsxiv -- "$@" # fallback
  fi
}

[ "$1" = '--' ] && shift
case "$1" in
  "") echo "Usage: ${0##*/} PICTURES" >&2; exit 1 ;;
  /*) open_img "$1" ;;
  "~"/*) open_img "$HOME/${1#"~"/}" ;;
  *) open_img "$PWD/$1" ;;
esac
