#!/bin/sh
countdown(){
	end=$(($(date +%s) +$1))
	while [ $end -ge $(date +%s) ]; do
		time=$(($end - $(date +%s)))
		# printf 'Time: %s\r' $(date -u -d @$time +%H:%M:%S)
		notify-send -a "pomodoro" -u low -i appointment-soon \
			-h string:x-dunst-stack-tag:pomodoro \
			-h int:value:$(($time *100 / $1)) \
			-t 3000 \
			"Pomodoro" "Time: $(date -u -d @$time +%H:%M:%S)\r"
		sleep 2
	done
}

settime=${1:-25}
if [ -n "${2+set}" ]; then
	interval=$settime
else
	interval=$(($settime *60))
fi
while true; do
	countdown $interval
	canberra-gtk-play -i alarm-clock-elapsed
done
