#!/bin/sh

dmenu() {
	fuzzel --dmenu "$@"
}

sel=$(echo -e "Start\nEnd\nReset\nStart Mins\nStart Secs" | dmenu -l 5)
if [ "$sel" = "End" ]; then
	pkill pomo
elif [ "$sel" = "Reset" ]; then
	pkill pomo
	pomo
elif [ "$sel" = "Start" ]; then
	pomo
elif [ "$sel" = "Start Mins" ]; then
	time=$(echo -e "25\n20\n10\n5" | dmenu -p "Time Mins:" -l 5)
	echo $time
	[ -z "$time" ] || pomo "$time"
elif [ "$sel" = "Start Secs" ]; then
	time=$(echo -e "25\n20\n10\n5" | dmenu -p "Time Secs:" -l 5)
	echo $time
	[ -z "$time" ] || pomo "$time" "s"
fi
