#!/bin/sh

menu="Poweroff\nSuspend\nLogout\nReboot"
ans="$(printf "$menu" | fuzzel --dmenu -p 'Power: ')"

case $ans in
Logout)
	killall lf
	hyprctl dispatch exit
	;;
Suspend)
	systemctl suspend
	;;
Reboot)
	sudo -A reboot
	;;
Poweroff)
	if pgrep openvpn; then
		notify-send -u "critical" "Powermenu" "OpenVPN is still up"
		exit
	else
		killall lf
		shutdown -h now
	fi
	;;
*)
	exit
	;;
esac
