#!/bin/sh

case "$(file --mime-type "$1" -L -b)" in
	application/json|text/*)
		highlight "$1" -s $HOME/.config/highlight/toft-colors.theme -O truecolor --force;;
	audio/*|video/*) audinfo "$1";;
	application/pdf) pdftotext -l 10 -nopgbrk -q -- "$1" -;;
	application/gzip|application/x-tar|application/zip|application/x-rar) printf "\e[0;30;44m Archived File List \e[0m\n" && bsdtar --list --file "$1" ;;
	inode/x-empty) printf "\e[0;30;43m Empty \e[0m\n" ;;
	application/x-executable) printf "\e[0;30;43m Executable \e[0m\n" ;;
	application/x-pie-executable) printf "\e[0;30;43m Pie Executable \e[0m\n" ;;
	*) printf "\e[0;33;40m $(file --dereference --brief -- "$1") \e[0m\n";;
esac
