#!/usr/bin/sh
# By github OliverLew
ID="lf-preview"
[ -p "$FIFO_UEBERZUG" ] || exit 1

# no arguments to clear
case "${1:-clear}" in
    draw)
        {   printf '{ "action": "add", "identifier": "%s", "path": "%s",' "$ID" "$2"
            printf '"width": %d, "height": %d, "x": %d, "y": %d }\n' "$3" "$4" "$5" "$6"
        } > "$FIFO_UEBERZUG" ;;
    clear|*)
		echo "a"
        printf '{ "action": "remove", "identifier": "%s" }\n' "$ID" > "$FIFO_UEBERZUG";;
esac
