#!/bin/sh
error_exit(){
	echo "$1" >&2
	exit
}
# VPN directory
prefix="${XDG_STATE_HOME-$HOME/.config}/runvpn"
[ -d "$prefix" ] || mkdir "$prefix"
cd "$prefix" || exit 1

#== Folder Format ==#
#runvpn
#	vpn_1
#		vpn_1.ovpn
#		vpn_1.txt
#	vpn_2
#		...

#== vpn_1.txt ==#
# username
# password
select_vpn(){
	vpn_folder=$(find . -mindepth 1 -type d -printf "%f\n" | dmenu -c -l 20 -p "VPN: ")
	if [ -z "$vpn_folder" ]; then
		exit 1
	else
		echo "$vpn_folder"
	fi
}

get_cmd(){
	cd "${prefix}/$1" || exit 1
	vpn_command="sudo openvpn --config $1.ovpn "
	# vpn_command="$TERMINAL -c openvpn -e sudo openvpn --config ${prefix}/${vpn_folder}/${vpn_folder}.ovpn "
	if [ -f "$1.txt" ]; then
		vpn_command="$vpn_command --auth-user-pass $1.txt"
	fi
	echo "$vpn_command"
}

dunsty(){
	dunstify -t 0 -i network-vpn-symbolic.symbolic -u low \
		--action="stop,Stop" \
		"VPN" "Running VPN ${vpn_folder}"
	echo "$ACTION"
}

if ! vpn_folder="$(select_vpn)"; then
	exit 1
fi
vpn_command="$(get_cmd "$vpn_folder")"
cd "${prefix}/${vpn_folder}" || exit 1
$vpn_command &

while true; do
	ACTION=""
	ACTION=$(dunsty)
	case "$ACTION" in
		"stop")
			if sudo -A pkill -15 openvpn; then
				dunstify -i network-vpn-symbolic.symbolic "VPN" "Disconnected VPN ${vpn_folder}"
			else
				dunstify -i network-vpn-symbolic.symbolic -u "critical" "VPN" "Could not connect to VPN"
			fi
			exit
			;;
	esac

done
