#!/bin/sh
default_dirs=`echo ~/Backgrounds/cultured ~/Backgrounds/unsafe`
safe_dir=~/Backgrounds/safe

if [ "$1" = "-h" ]; then
  echo "Usage: $0 [Image or Directory]"
  exit 1
fi

# if $@ does not exist, use default_dir
file_list="$@"
if [ "$1" = "safe" ]; then
  # if 1st argument is file, file mode
  image=$(find $safe_dir -type f | shuf -n 1)
elif [ -f "$1" ]; then
  # if 1st argument is file, file mode
  image="$1"
else
  # dir mode
  : ${file_list:=$default_dirs}
  image=$(find $file_list -type f | shuf -n 1)
fi

if [ -z "$image" ]; then
	echo "Error: Argument '$arg' is not image or directory" >&2
  exit 1
fi

if ! swww query &>/dev/null; then
  swww init --no-cache
  # If not started, set image directly, no transition
  swww img "$image"
else
  swww img "$image" --transition-type wipe
fi

