#!/bin/sh
set -Eeuo pipefail
usage(){
  cat <<EOF
Usage:
  wallpaper [-d root] [wallpaper directory name]
  wallpaper [-f local image or directory]
EOF
}

root="$HOME/Backgrounds"
default=""
local=""

OPTIND=1
while getopts ":hd:f:" arg; do
  case $arg in
  d) root="$OPTARG" ;;
  f) local="$OPTARG" ;;
  h) usage; exit 0 ;;
  \?) echo "Invalid option: -$OPTARG"
    usage; exit 1;;
  :) echo "Option -$OPTARG requires an argument"
    usage; exit 1;;
  esac
done

# Shift to Required arguments
shift $((OPTIND-1))

if [ ! -z "$local" ]; then
  # Local File
  if [ -f "$local" ]; then
    image="$local"
  elif [ -d "$local" ]; then
    image=$(find "$local" -type f | shuf -n 1)
  else
    echo "Argument '$local' is not a file or directory"
    usage; exit 1
  fi
else
  # Not local
  if [ "$#" -lt 1 ] || [ -z "$1" ]; then
    image="$(find "$root/$default" -type f | shuf -n 1)"
  elif [ -f "$root/$1" ]; then
    image="$1"
  elif [ -d "$root/$1" ]; then
    image="$(find "$root/$1" -type f | shuf -n 1)"
  else
    echo "Argument '$1' is not a file or directory in '$root'"
    usage; exit 1
  fi
fi

if [ -z "$image" ]; then
	echo "Error: Argument '$arg' is not image or directory" >&2
  exit 1
fi

if ! swww query &>/dev/null; then
  swww init --no-cache
  # If not started, set image directly, no transition
  swww img "$image"
else
  swww img "$image" --transition-type wipe
fi
