#!/bin/sh

prompt(){
	dmenu -c -l 10 -p "$1"
}
error_exit(){
	echo "$1" >&2
	exit 1
}
notify_ok(){
	notify-send -i "network-wireless-signal-excellent-symbolic.symbolic" "Wifi Connection" "$1"
}

notify_bad(){
	notify-send -i "network-wireless-signal-excellent-symbolic.symbolic" -u "critical" "Wifi Connection" "$1"
	error_exit "$1"
}

stat=$(nmcli -fields TYPE,DEVICE,CONNECTION d | grep "wifi[^-]" | sed 's/ \+/ /g')
wifi=$(echo "$stat" | cut -f 3 -d " ")
dev_name=$(echo "$stat" | cut -f 2 -d " ")
prompt="Connect"

if [ ! "$wifi" = "--" ]; then
	prompt="Connect\nDisconnect"
fi
command=$(printf "$prompt" | prompt "Connection: ")

case "$command" in
	Connect)
		ssid=$(nmcli -f BARS,SSID dev wifi list | sed '1d' | prompt "Connect: " | sed -e 's/ \+/ /' -e 's/ *$//'| cut -f 2- -d " ")
		[ -z "$ssid" ] && error_exit "No SSID provided"
		memory=$(nmcli -f NAME con show | grep "$ssid" | head -1 | sed -e 's/ \+/ /' -e 's/ *$//')
		if [ "${memory}" = "${ssid}" ]; then
			if nmcli dev wifi connect "${ssid}"; then
				notify_ok "Connected to $ssid"
			else
					notify_bad "Could not connect to $ssid"
			fi
		else
			pass="$(ask_password)"
			if nmcli dev wifi connect "${ssid}" password "${pass}"; then
				notify_ok "Connected to $ssid"
			else
				notify_bad "Could not connect to $ssid"
			fi
		fi
		;;
	Disconnect)
		if nmcli dev disconnect "$dev_name"; then
			notify_ok "Disconnected $dev_name"
		else
			notify_bad "Could not disconnect $dev_name"
		fi
		;;
esac
